### ISSUE TITLE
Thunarのサイドにダウンロードなどの項目を追加する

### ISSUE THREAD

**Issue by hyuoou** [hyuoou/GrowthLinux#10]

**Comment by Hayao0819** [comment]
alterlinux-live-toolsのalterlinux-gtk-bookmarksを使用してみてください

https://github.com/FascodeNet/alterlinux-live-tools/tree/master/alterlinux-gtk-bookmarks

https://github.com/FascodeNet/alterlinux/blob/dev-stable/channels/xfce/airootfs.any/etc/skel/.config/autostart/gensidebar.desktop

**Comment by hyuoou** [comment]
ありがとうございます。追加することができました。
